-- CreateTable
CREATE TABLE "OtpCode" (
    "phone" TEXT NOT NULL PRIMARY KEY,
    "hash" TEXT NOT NULL,
    "expiresAt" DATETIME NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
